site_name: Poco Documentation
site_description: Documentation for the Poco simulation engine for power and cover curve analysis
site_author: Your Name

repo_url: https://github.com/ls008z/poco
edit_uri: edit/main/docs/

theme:
  name: material
  palette:
    primary: indigo
    accent: indigo
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.expand
    - navigation.indexes
    - content.code.copy

nav:
  - Home: index.md
  - Installation: installation.md
  - Usage Guide: usage.md
  - Key Concepts: concepts.md
  - API Reference: api.md
  - Development Roadmap: roadmap.md
  - Contributing: ../CONTRIBUTING.md
  - Changelog: ../CHANGELOG.md

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true

plugins:
  - search

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js